### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by benfluleck** [loeck/react-progress-circle2#1]
How do you convert the size number into 'px'? You are using default size 40 but I can't see how it is getting converted to px for the div height and width.

**Comment by loeck** [comment]
Hey !

It's just React stuff, React converte automatically some style attributes to `px` (as here: https://github.com/loeck/react-progress-circle2/blob/master/src/index.js#L55)

**Comment by benfluleck** [comment]
This is alright i think it is CSS but this means I cannot specify a value of 6rem?

**Comment by loeck** [comment]
Ah yes, I understand your issue, but I need a value in `px`, for calculate radius (see https://github.com/loeck/react-progress-circle2/blob/master/src/index.js#L40) based on circle size, I "think" if I use a size in `em` or `rem` I might have some issues.

**Comment by benfluleck** [comment]
You could have separate logic for calculation of the SVG parameters and the div container surrounding it Or you can use an endsWith function in JS to strip of the words at the end. 
This way we can specify a bunch of types you can handle. I think I pick the first option because the calculation of rem and maybe em is different from px.

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
IAmMorrow, @bettabacon, @Jayser23, @Arnaud97234, @mebmc, @TommyFedoraHR, @reillybeacom, @LO-COLoar, @maplewaffle, @Snooza, @noprom, @wrenegade1, @ngarnier, @unlink2, @wang502, @dalexhd, @andythekid, @adamhemzal, @shunjizhan, @icyfry, @paul1tsch, @tomfotherby, @dalakatt, @Dikyx, @Wizyma, @Roon, @craigwblake, @Georgezhang714, @DrGetDown, @ahaneef29, @burakince, @erings, @wyn, @Neo42, @cbeydon-ledger, @teams2ua, @suvayu, @insiderq, @squirlin, @tony-xsr, @ITRussell, @ReidDecentral, @sonny-chen, @incomingstick, @om2c0de, @ephammer, @Schreibmaschinespricht, @chmichael, @netindev, @2GMon

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
EricCrosson, @cbarnettx, @labelexe, @kenfromb, @JesusMtnez, @Vic23M, @248311, @battd13, @nfsc-tommy, @AdrianBesleaga, @crimeminister, @cqgsm, @halfwolf0x, @sadiqevani, @Butterfliesinspacejoe, @TheBadListener, @HenryWu01, @bertrell, @sfx101, @tombertrand, @suchat932, @LukaszGost, @SHagege, @tblakex01, @ouyun, @21gramzz, @rstms, @804165409, @idimaa, @Xeno8, @amal, @ashchan, @kenneth, @caitif69, @JayJarosz, @luciorubeens, @WUZICANGJIE, @chester-tan, @KKSSCHOI, @Th0rgal, @DrangPo, @acgloli, @0x11DFE, @the-cc-dev, @fairlighteth, @cotin18, @matteocng, @erdnussflips, @includeleec, @Gustiagstn
